export let products = [
    {
        id: 1,
        name: 'North Korea 1977/1988 - Batch with 224 blocks and sheets',
        geographicOrigin: 'North Korea',
        year: '1977-1988 (from the oldest to the most recent)',
        condition: 'Cancelled',
        category: 'stamps',
        lastBid: 177,
        sellerName: 'John Doe',
        sellerCountry: 'France',
        isVerified: false,
        soldProducts: 252,
        sellerRating: 1,
        src: require( '@/core/shared/components/images/stamps/stamp1.jpeg' )
    },
    {
        id: 2,
        name: 'China - 1878-1949 1923/1926 - Definitive values - #65-68',
        geographicOrigin: 'China - 1878-1949',
        year: '1923-1926 (from the oldest to the most recent)',
        condition: 'MNH (Mint never hinged)',
        category: 'stamps',
        lastBid: 17,
        sellerName: 'Javier Nitto',
        sellerCountry: 'France',
        isVerified: false,
        soldProducts: 142,
        sellerRating: 2,
        src: require( '@/core/shared/components/images/stamps/stamp2.jpeg' )
    },
    {
        id: 3,
        name: 'Netherlands 1945/2007 - Collection in four DAVO albums',
        geographicOrigin: 'Netherlands',
        year: '1945-2007 (from the oldest to the most recent)',
        condition: 'MNH (Mint never hinged)',
        category: 'stamps',
        lastBid: 200,
        sellerName: 'Sergio Bonnuci',
        sellerCountry: 'Italy',
        isVerified: true,
        soldProducts: 12,
        sellerRating: 4,
        src: require( '@/core/shared/components/images/stamps/stamp3.jpeg' )
    },
    {
        id: 4,
        name: 'Germany, Federal Republic 1949/1950 - Two years - Michel 111/122',
        geographicOrigin: 'Germany, Federal Republic',
        year: '1949-1950 (from the oldest to the most recent)',
        condition: 'MNH (Mint never hinged)',
        category: 'stamps',
        sellerName: 'John Wick',
        sellerCountry: 'Kanada',
        isVerified: true,
        soldProducts: 2252,
        lastBid: 1110,
        sellerRating: 5,
        src: require( '@/core/shared/components/images/stamps/stamp4.jpeg' )
    },
    {
        id: 5,
        name: 'Italian Ancient States - Modena 1852 - Emissione con punto dopo la cifra c.40 azzurro con punto presso il 4 - Sassone N. 10b',
        geographicOrigin: 'Italian Ancient States - Modena',
        year: '1852',
        condition: 'Used',
        category: 'stamps',
        sellerName: 'Marina Apolkova',
        sellerCountry: 'Russia',
        isVerified: false,
        soldProducts: 300,
        lastBid: 300,
        sellerRating: 3,
        src: require( '@/core/shared/components/images/stamps/stamp5.jpeg' )
    },
    {
        id: 6,
        name: 'Italian Ancient States - Modena 1859 - Provisional Government, c. 40 carmine + c. 80 orange bistre - N. 17 + 18',
        geographicOrigin: 'Italian Ancient States - Modena',
        year: '1859',
        condition: 'MH (Mint hinged)',
        category: 'stamps',
        sellerName: 'Marcel Burleau',
        sellerCountry: 'France',
        isVerified: true,
        soldProducts: 113,
        lastBid: 40,
        sellerRating: 1,
        src: require( '@/core/shared/components/images/stamps/stamp6.jpeg' )
    },
    {
        id: 7,
        name: 'Japan. Tokugawa Coinage. Man-en Koban Gold (1 Ryo) ND 1860-1867',
        geographicOrigin: 'Japan',
        year: '1860-1867',
        condition: 'MH (Mint hinged)',
        category: 'coins',
        sellerName: 'Pine del Niero',
        sellerCountry: 'Columbia',
        isVerified: false,
        soldProducts: 111,
        lastBid: 17,
        sellerRating: 5,
        src: require( '@/core/shared/components/images/coins/coin1.jpeg' )
    },
    {
        id: 8,
        name: 'Portugal. D. Pedro IV (1826-1828). Meia Peça (3.200 Reis) 1827 - Escassa',
        geographicOrigin: 'Portugal',
        year: '1826–1828',
        condition: 'MNH (Mint never hinged)',
        category: 'coins',
        sellerName: 'Bryan Burton',
        sellerCountry: 'Kanada',
        isVerified: false,
        soldProducts: 10,
        lastBid: 900,
        sellerRating: 4,
        src: require( '@/core/shared/components/images/coins/coin2.jpeg' )
    },
    {
        id: 9,
        name: 'France. Jean II le Bon (1350-1364). Ecu d\'or à la chaise',
        geographicOrigin: 'France',
        year: '1350-1364',
        condition: 'Used',
        category: 'coins',
        sellerName: 'Bella Bartha',
        sellerCountry: 'Hungary',
        isVerified: true,
        soldProducts: 90,
        lastBid: 170,
        sellerRating: 2,
        src: require( '@/core/shared/components/images/coins/coin3.jpeg' )
    },
    {
        id: 10,
        name: 'Portugal. D. João III (1521-1557). Tostão (100 Reais) - L R - Lisboa - ΛL.D:G/VINCESS',
        geographicOrigin: 'Portugal',
        year: '1521-1557',
        condition: 'Used',
        category: 'coins',
        sellerName: 'Janson Stan',
        sellerCountry: 'USA',
        isVerified: true,
        soldProducts: 1100,
        lastBid: 1512,
        sellerRating: 2,
        src: require( '@/core/shared/components/images/coins/coin4.jpeg' )
    },
    {
        id: 11,
        name: 'Corsica. Pascal Paoli. 4 Soldi 1765',
        geographicOrigin: 'France',
        year: '1765',
        condition: 'Ungraded',
        category: 'coins',
        sellerName: 'Elizabeth Smith',
        sellerCountry: 'Kanada',
        isVerified: false,
        soldProducts: 200,
        lastBid: 12,
        sellerRating: 5,
        src: require( '@/core/shared/components/images/coins/coin5.jpeg' )
    }
];